feat: Implement conversation logic and enhance validations
books4u-tcc/backend pull request #3
Opened 2024-09-18 22:53 UTC by Joao-Messias

2024-09-18 22:56 UTC, metehus requested changes

2024-09-18 22:56 UTC, metehus commented on src/dto/create-conversation.dto.ts
> +  title: string;
aqui eu acho que o title precisa ser criado no back (pela IA), já que não tem como o front saber qual vai ser o titulo

2024-09-18 23:37 UTC, Joao-Messias commented on src/dto/create-conversation.dto.ts
> +  title: string;
Pode aprovar, vou integrar com IA, e depois modifico esse endpoint quando tiver integrado

2024-09-19 13:24 UTC, metehus approved these changes

2024-09-20 00:40 UTC, merged