feat: Implement conversation logic and message-saving structure
books4u-tcc/backend pull request #4
Opened 2024-09-20 04:14 UTC by Joao-Messias

# Implementação da Lógica de Conversação e Estrutura de Salvamento de Mensagens

## Descrição:

Este PR traz as seguintes mudanças e melhorias na aplicação:

- **Novo módulo de mensagens**: Foi criado o `MessageModule` e `MessageService` para gerenciar o salvamento e recuperação de mensagens associadas às conversas.
  
- **Integração com o OpenAI**: Implementada a integração com a API da OpenAI, permitindo a criação de threads e a interação com o assistente de forma contínua dentro das conversas.

- **Lógica de criação de conversas**: Agora, ao criar uma nova conversa, a primeira mensagem do assistente gerada pela API da OpenAI é automaticamente salva no banco de dados.

- **Migração de banco de dados**: Criada uma nova migração para adicionar o campo `threadId` na entidade `Conversation`, necessário para armazenar o ID da thread gerada pela OpenAI.

- **Melhorias estruturais**: Validações aprimoradas e organização dos serviços de mensagens e conversas para otimizar o fluxo de dados e o funcionamento geral da aplicação.

### Como testar:
1. Criar uma nova conversa utilizando a API `/conversations`.
2. Verificar que a conversa foi criada no banco de dados com o campo `threadId`.
3. Garantir que a primeira mensagem gerada pelo assistente da OpenAI é salva e pode ser recuperada.
4. Enviar uma mensagem usando a api para enviar mensagem do usuario
5. Recuperar essa mensagem e verificando q o endpoint de verificar as mensagens de uma conversa, estão retornando formatadas da maneira correta, e na ordem correta e no padrão correto. E garantir que está sendo salvo no banco de dados.

Falta algumas coisas pra melhorar ainda, referente ao que eu fiz:

1. Salvar as recomendações no banco de dados.
2. Ajustar a maneira de salvar as sugestões na tabela de mensagens.
3. Melhorar a maneira de retornar as recomendações geradas no endpoint de verificar mensagens

2024-09-25 23:29 UTC, metehus requested changes

2024-09-25 23:29 UTC, metehus commented on src/openai/openai.service.ts
> +
aqui precisa de pooling? se o endpoint de criar run retornar normalmente a resposta, podemos pegar de la. Se não acho que da pra usar o streaming e coletar todos os tokens por eventos: https://platform.openai.com/docs/assistants/quickstart?context=with-streaming

2024-09-30 02:35 UTC, metehus requested changes

2024-09-30 02:35 UTC, metehus commented on src/conversations/conversation.controller.ts
>      const user = req.user as Account;
é possivel criar conversas e mandar mensagens mesmo deslogado, precisa alterar aqui pra possibilitar isso

2024-09-30 02:40 UTC, metehus commented on src/conversations/conversation.controller.ts
> +    const messages = await this.openAiService.getMessages(threadId);
outra coisa: isso aqui ta errado. o flxuo é o usuário que inicia a conversa com uma primeira mensagem, que nem no chatgpt.

2024-09-30 02:52 UTC, metehus commented on src/conversations/conversation.controller.ts
> +    return { userMessage };
aqui ta retornando a propria msg que o usuario enviou. não deveria retornar a resposta da IA?

2024-10-15 18:29 UTC, guedesz reviewed
excelente

2024-10-15 18:47 UTC, metehus approved these changes

2024-10-15 18:56 UTC, merged